export const SIGNIN = 'SIGNIN';


// UserDetailActions
export const REQUST_USER_DETAILS = 'REQUEST_USER_DETAILS';
export const RECEIVE_USER_DETAILS = 'RECEIVE_USER_DETAILS';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';